version: "3.3"

services:
    mysql_server:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/db-data:/var/lib/mysql
        environment:
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            MYSQL_DATABASE: docker
            MYSQL_ROOT_PASSWORD: docker
    nginx:
        image: nginx:1.19
        ports:
            - "80:80"
